"""Ed25519 release key handling and signed-document envelopes."""

from __future__ import annotations

import base64
import hashlib
import os
from copy import deepcopy
from pathlib import Path
from typing import Any

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from .canonical import canonical_bytes, write_json

ALGORITHM = "Ed25519"


class SignatureError(ValueError):
    pass


def _public_raw(key: Ed25519PublicKey) -> bytes:
    return key.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def key_id(key: Ed25519PublicKey) -> str:
    return hashlib.sha256(_public_raw(key)).hexdigest()


def public_metadata(key: Ed25519PublicKey) -> dict[str, Any]:
    raw = _public_raw(key)
    return {
        "algorithm": ALGORITHM,
        "key_id": hashlib.sha256(raw).hexdigest(),
        "public_key_base64": base64.b64encode(raw).decode("ascii"),
        "schema_version": 1,
    }


def swift_public_key(metadata: dict[str, Any]) -> str:
    return (
        "// Generated by forge-release. Public material only.\n"
        "enum ForgeReleaseKey {\n"
        f'    static let algorithm = "{metadata["algorithm"]}"\n'
        f'    static let keyID = "{metadata["key_id"]}"\n'
        f'    static let base64 = "{metadata["public_key_base64"]}"\n'
        "}\n"
    )


def generate_keypair(
    private_path: Path | str,
    public_metadata_path: Path | str,
    swift_path: Path | str | None = None,
) -> dict[str, Any]:
    private_target = Path(private_path)
    if private_target.exists():
        raise FileExistsError(f"refusing to overwrite private key: {private_target}")
    private_target.parent.mkdir(parents=True, exist_ok=True)
    key = Ed25519PrivateKey.generate()
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    descriptor = os.open(private_target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "wb") as output:
        output.write(pem)
        output.flush()
        os.fsync(output.fileno())
    metadata = public_metadata(key.public_key())
    write_json(public_metadata_path, metadata)
    if swift_path is not None:
        target = Path(swift_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(swift_public_key(metadata), encoding="utf-8")
    return metadata


def load_private_key(path: Path | str) -> Ed25519PrivateKey:
    key = serialization.load_pem_private_key(Path(path).read_bytes(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise TypeError("release key is not Ed25519")
    return key


def load_public_key(path: Path | str) -> Ed25519PublicKey:
    metadata = __import__("json").loads(Path(path).read_text(encoding="utf-8"))
    if metadata.get("algorithm") != ALGORITHM or metadata.get("schema_version") != 1:
        raise SignatureError("unsupported public-key metadata")
    try:
        raw = base64.b64decode(metadata["public_key_base64"], validate=True)
    except (KeyError, ValueError) as error:
        raise SignatureError("invalid public key encoding") from error
    key = Ed25519PublicKey.from_public_bytes(raw)
    if key_id(key) != metadata.get("key_id"):
        raise SignatureError("public key ID mismatch")
    return key


def sign_document(document: dict[str, Any], private_key: Ed25519PrivateKey) -> dict[str, Any]:
    if "signature" in document:
        raise SignatureError("unsigned document must not contain signature")
    signed = deepcopy(document)
    signature = private_key.sign(canonical_bytes(document))
    signed["signature"] = {
        "algorithm": ALGORITHM,
        "key_id": key_id(private_key.public_key()),
        "value_base64": base64.b64encode(signature).decode("ascii"),
    }
    return signed


def verify_document(document: dict[str, Any], public_key: Ed25519PublicKey) -> dict[str, Any]:
    signature = document.get("signature")
    if not isinstance(signature, dict):
        raise SignatureError("document is unsigned")
    if signature.get("algorithm") != ALGORITHM or signature.get("key_id") != key_id(public_key):
        raise SignatureError("signature key or algorithm mismatch")
    unsigned = deepcopy(document)
    del unsigned["signature"]
    try:
        encoded = base64.b64decode(signature["value_base64"], validate=True)
        public_key.verify(encoded, canonical_bytes(unsigned))
    except (InvalidSignature, KeyError, ValueError) as error:
        raise SignatureError("invalid document signature") from error
    return unsigned
