FROM docker.io/library/ubuntu@sha256:b7f48194d4d8b763a478a621cdc81c27be222ba2206ca3ca6bc42b49685f3d9e

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        autoconf automake bash bazel-bootstrap black build-essential ccache clang clang-format \
        clang-tidy clangd cmake conan cppcheck curl g++ gcc gdb git lld lldb llvm make meson \
        mypy ninja-build pipx pkg-config python3 python3-dev python3-pip python3-pytest \
        python3-venv rust-clippy rustc rustfmt cargo scons shellcheck tox valgrind \
    && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/forge/bin:$PATH \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIPX_HOME=/opt/pipx \
    PIPX_BIN_DIR=/opt/forge/bin \
    UV_LINK_MODE=copy

RUN install -d -m 0755 /opt/forge/bin \
    && pipx install uv \
    && pipx install poetry \
    && pipx install pyright \
    && pipx install ruff

RUN git clone --filter=blob:none --no-checkout https://github.com/microsoft/vcpkg.git /opt/vcpkg \
    && git -C /opt/vcpkg checkout --detach cd61e1e26a038e82d6550a3ebbe0fbbfe7da78e3 \
    && /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics \
    && ln -s /opt/vcpkg/vcpkg /opt/forge/bin/vcpkg

WORKDIR /workspace
LABEL org.opencontainers.image.title="Forge C C++ Rust Python Workstation" \
      org.opencontainers.image.source="https://github.com/Bit-Loop/forge-for-ipad" \
      org.opencontainers.image.licenses="Apache-2.0"
